<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Saluja-16" ignored="0" name="Default test" tests="3" failures="1" timestamp="04 Mar 2018 08:38:39 GMT" time="259.237" errors="0">
  <testcase name="feature" time="66.333" classname="demo.AesopAshDemo.UserTest"/>
  <testcase name="feature" time="65.171" classname="demo.AesopAshDemo.UserTest">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: The following asserts failed:
	expected [Title] but found [No Title]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: The following asserts failed:expected [Title] but found [No Title]at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)at demo.AesopAshDemo.UserTest.feature(UserTest.java:31)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: java.lang.AssertionError: The following asserts failed:expected [Title] but found [No Title]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at demo.AesopAshDemo.TestSteps.signup_window(TestSteps.java:129)at âœ½.Then Screen appears with Title, Firstname and Lastname(feature_2.feature:6)]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="127.274" classname="demo.AesopAshDemo.UserTest"/>
</testsuite> <!-- Default test -->
